// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0AwxTrztHws-PGmrGrifDWcZ_IbOdJ0',
    appId: '1:746395364182:web:e8eeff1b1935251216c4f7',
    messagingSenderId: '746395364182',
    projectId: 'rositafresita03xd',
    authDomain: 'rositafresita03xd.firebaseapp.com',
    storageBucket: 'rositafresita03xd.firebasestorage.app',
    measurementId: 'G-XTYSZFE0Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGrLCCZDnwkvF9iUQrpyGLG_5fE5ov4QE',
    appId: '1:746395364182:android:27655f234062216d16c4f7',
    messagingSenderId: '746395364182',
    projectId: 'rositafresita03xd',
    storageBucket: 'rositafresita03xd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALWf0CUm0Xy-NGLBCzrgeDw58g2KhNF0c',
    appId: '1:746395364182:ios:ddad0969fb9d312f16c4f7',
    messagingSenderId: '746395364182',
    projectId: 'rositafresita03xd',
    storageBucket: 'rositafresita03xd.firebasestorage.app',
    iosBundleId: 'com.example.smartGas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALWf0CUm0Xy-NGLBCzrgeDw58g2KhNF0c',
    appId: '1:746395364182:ios:ddad0969fb9d312f16c4f7',
    messagingSenderId: '746395364182',
    projectId: 'rositafresita03xd',
    storageBucket: 'rositafresita03xd.firebasestorage.app',
    iosBundleId: 'com.example.smartGas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV0AwxTrztHws-PGmrGrifDWcZ_IbOdJ0',
    appId: '1:746395364182:web:5e6a1b8ce565288f16c4f7',
    messagingSenderId: '746395364182',
    projectId: 'rositafresita03xd',
    authDomain: 'rositafresita03xd.firebaseapp.com',
    storageBucket: 'rositafresita03xd.firebasestorage.app',
    measurementId: 'G-8Z5LN4W38Z',
  );
}
